#!/bin/sh

if [ $# -eq 1 ]
then

	find -L *|xargs grep $1

else 
	if [ $# -eq 2 ]
	then
	
		find -L . -name "*.$2*" -nowarn |xargs grep $1

	else

		echo Donner le nom du fichier à chercher
		exit 1
	fi
fi 
